version: "3.8"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      SECRET_KEY: ${SECRET_KEY}
      COMPANY_NAME: ${COMPANY_NAME}
      ALLOWED_EXTENSIONS: ${ALLOWED_EXTENSIONS}
      APPROVERS: ${APPROVERS}
    volumes:
      - .:/app:ro
      - C:/rms/uploads:/app/static/uploads

volumes:
  pgdata:
