"""add two-step approval columns to Return

Revision ID: 1c779d5fc396
Revises: 18048b1e7431
Create Date: 2025-06-23 14:10:45.424771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c779d5fc396'
down_revision = '18048b1e7431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('return_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('mimetype',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('return_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.alter_column('return_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.alter_column('return_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('return_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('mimetype',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('return_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
