"""add two-step approval columns to Return

Revision ID: db1e6686d31d
Revises: 1c779d5fc396
Create Date: 2025-06-23 14:15:05.487772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1e6686d31d'
down_revision = '1c779d5fc396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wh_approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wh_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mgr_approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mgr_approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['wh_approved_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['mgr_approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mgr_approved_at')
        batch_op.drop_column('mgr_approved_by')
        batch_op.drop_column('wh_approved_at')
        batch_op.drop_column('wh_approved_by')

    # ### end Alembic commands ###
