name: CI + Deploy

on:
  push:
    branches: [ "main" ]      # deploy only from main
  pull_request:
    branches: [ "main" ]      # CI still runs for PRs

jobs:

  # ── 1. CI: install + unit test ────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Optional: run a minimal app import test
        python -c "import rms, sys; sys.exit(0)"

    - name: Create ZIP artefact
      if: github.ref == 'refs/heads/main'
      run: |
        7z a ReturnApp.zip . -xr!venv -xr!.git
      shell: bash

    - name: Upload artefact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: ReturnApp
        path: ReturnApp.zip

  # ── 2. Deploy to IIS (only on main) ───────────────────────────────────────
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Download artefact
      uses: actions/download-artifact@v4
      with:
        name: ReturnApp

    - name: Copy to Windows server via WinRM
      uses: jborean93/psrp-action@v2               # simple PowerShell-Remoting action
      with:
        hostname: ${{ 10.4.21.4 }}
        username: ${{ TWORIVERS\Kush }}
        password: ${{ Baw05622 }}
        script: |
          param($Artifact)
          $dest = 'C:\deploy\ReturnApp.zip'
          Copy-Item $Artifact $dest -Force
          Expand-Archive $dest -DestinationPath 'C:\deploy\ReturnApp' -Force
          # sync to IIS folder (robocopy preserves app_offline.htm if you ever use it)
          robocopy C:\deploy\ReturnApp C:\inetpub\ReturnApp /MIR /XF web.config app_offline.htm
          # install new libs (assumes venv Scripts is on PATH)
          C:\inetpub\ReturnApp\venv\Scripts\pip.exe install -r C:\inetpub\ReturnApp\requirements.txt
          iisreset /restart
          nssm restart ReturnApp-CeleryWorker
          nssm restart ReturnApp-CeleryBeat
      env:
        Artifact: ReturnApp.zip
